# Generated by Django 5.0 on 2023-12-15 18:01

import image_optimizer.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=image_optimizer.fields.OptimizedImageField(blank=True, null=True, upload_to='images/users'),
        ),
    ]
